# Date: 8-Jul-2019 jdw split out from original pipeline
# Supports: fixtures=mysql,mongodb (linux)
#
# Updates:
#  6-Aug-2019  jdw build source and binary wheels by default.
# 13-Aug-2019  jdw export config support token prior to launching tox runner
# 24-Nov-2020  jdw add py39 support
# 10-Oct-2024  mjt add py310 support, macos-12 -> macos-13, ubuntu 20 -> ubuntu 22
#  8-Dec-2025  dwp add py313 support, standardize template
##
parameters:
  tox: ""
  python: ""
  os: "linux"
  fixtures: ""

jobs:
  - job: ${{ format('build_test_{0}_{1}', parameters.tox, parameters.os) }}
    timeoutInMinutes: 0
    pool:
      ${{ if eq(parameters.os, 'macos') }}:
        vmImage: "macOS-15"
      ${{ if eq(parameters.os, 'linux') }}:
        vmImage: "ubuntu-latest"

    variables:
      - group: py-shared-variables

    steps:
      #
      # ensure the required Python versions are available
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.python }}
          addToPath: true
        displayName: setup python
      #
      - checkout: self
        submodules: true
        fetchDepth: 1
      #
      - ${{ if startsWith(parameters.os, 'macos') }}:
          - bash: |
              set -e
              ls -la /Applications/Xcode*
              sudo xcode-select --switch /Applications/Xcode_16.app/Contents/Developer
              which g++
              c++ --version
            displayName: "setup Xcode"
          #
          - script: which brew
            displayName: "Check package manager"
          - script: brew install flex
            displayName: "Install flex"
          - script: which flex
            displayName: "Check flex"
          - script: brew install bison
            displayName: "Install bison"
          - script: which bison
            displayName: "Check bison"
          #
          - script: brew install mmseqs2
            displayName: "Install mmseqs2"
          - script: which mmseqs
            displayName: "Check mmseqs2"
          #
      # ----------------------------------------------
      - ${{ if startsWith(parameters.os, 'linux') }}:
          - script: lsb_release -a
            displayName: "Ubuntu kernel version"
          - script: which apt
            displayName: "Installing OS dependencies"
          - script: apt-cache policy | grep http | awk '{print $2 $3}' | sort -u
            displayName: "Checking for repos"
          #
          - script: sudo apt-get update
            displayName: "update apt"
          - script: sudo apt-get install flex
            displayName: "Install flex"
          - script: sudo apt-get install bison
            displayName: "Install bison"
      #
      - ? ${{ if and(contains(parameters.fixtures, 'mmseqs2'), startsWith(parameters.os, 'linux')) }}
        : - bash: |
              [ $(uname -m) = "x86_64" ] && echo "64bit: Yes" || echo "64bit: No"
              grep -q sse4_1 /proc/cpuinfo && echo "SSE4.1: Yes" || echo "SSE4.1: No"
              grep -q avx2 /proc/cpuinfo && echo "AVX2: Yes" || echo "AVX2: No"
            displayName: "Check architecture"
          - bash: |
              echo "Downloading latest MMseqs2 static build"
              attempt=1
              while [[ $attempt -le 5 ]]; do
                  wget https://mmseqs.com/latest/mmseqs-linux-avx2.tar.gz
                  if [[ $? -eq 0 ]]; then
                      echo "Download successful."
                      break
                  else
                      echo "Download failed. Retrying in 5 seconds..."
                      sleep 5
                      attempt=$((attempt + 1))
                  fi
              done
              tar xvzf mmseqs-linux-avx2.tar.gz
              sudo cp mmseqs/bin/mmseqs /usr/local/bin/mmseqs
            displayName: "Install mmseqs2 binary"
      #
        # -----
      - ? ${{ if and(contains(parameters.fixtures, 'mongodb'), startsWith(parameters.os, 'linux')) }}
        : # Mongo install
          - script: |
              sudo apt-get install gnupg curl
              curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
              sudo apt list --installed | grep mongodb
              echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
              sudo apt-get update
              sudo apt-get install -y mongodb-org
              sudo apt list --installed | grep mongo
            displayName: "Installing mongodb"
          #
          - script: |
              sudo service mongod start
              sudo ss -tulpn
            displayName: "Start Mongo service"
        #
      #
      - script: 'python -c "import sys; print(sys.version); print(sys.executable)"'
        displayName: show python information
      #
      - script: python -m pip install --upgrade pip tox
        displayName: "Install tools"
        #
      - script: pip install .[tests] --extra-index-url https://pypi.anaconda.org/OpenEye/simple
        displayName: "Install dependencies"
      #
      - task: DownloadSecureFile@1
        name: oelicense
        displayName: "Download OE license file"
        inputs:
          secureFile: "oe_license.txt"

      - ${{ if startsWith(parameters.tox, 'py') }}:
          - script: |
              export OE_LICENSE=$(oelicense.secureFilePath)
              export CONFIG_SUPPORT_TOKEN_ENV=$(VAR_CONFIG_SUPPORT_TOKEN_ENV)
              export PIP_EXTRA_INDEX_URL="https://pypi.anaconda.org/OpenEye/simple"
              ${{ format('python -m tox -e {0}', parameters.tox) }}
            displayName: "Running tox task"
      - ? ${{ if and(not(startsWith(parameters.tox, 'py')), startsWith(parameters.python, '3.12')) }}
        : - script: |
              export OE_LICENSE=$(oelicense.secureFilePath)
              export CONFIG_SUPPORT_TOKEN_ENV=$(VAR_CONFIG_SUPPORT_TOKEN_ENV)
              export PIP_EXTRA_INDEX_URL="https://pypi.anaconda.org/OpenEye/simple"
              ${{ format('python -m tox -e {0}-py312', parameters.tox) }}
            displayName: "Running tox task"
      #
      #  Build artifacts if this is a test target (i.e. labeled as py##)
      #
      - ${{ if startsWith(parameters.tox, 'py') }}:
          - script: pip install --upgrade pip build twine hatch
            displayName: "Acquire build tools"
          - script: python -m build --sdist --wheel --outdir "$(System.DefaultWorkingDirectory)/dist"
            displayName: "Build source and wheel distributions"
          #
          # Check the install artifacts
          - script: ls -lR "$(System.DefaultWorkingDirectory)/dist"
            displayName: "Listing of installed software"
          #
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: ${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}
        #
